# Generated by Django 5.1.4 on 2025-01-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_wishlist_products_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='available_products',
            field=models.ManyToManyField(blank=True, related_name='available_products', to='store.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='chosen_products',
            field=models.ManyToManyField(blank=True, related_name='chosen_products', to='store.product'),
        ),
    ]
