# Generated by Django 5.1.4 on 2025-01-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_wishlist_products_wishlist_available_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='available_products',
            field=models.ManyToManyField(related_name='available_in_wishlists', to='store.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='chosen_products',
            field=models.ManyToManyField(related_name='chosen_in_wishlists', to='store.product'),
        ),
    ]
