# Generated by Django 5.1.4 on 2025-01-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_wishlist_available_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='available_products',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='chosen_products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.JSONField(default=list),
        ),
    ]
