# Generated by Django 5.1.4 on 2025-01-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_wishlist_product_wishlist_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
