# Generated by Django 5.1.4 on 2025-01-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_wishlist_products_wishlist_item_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='user_email',
        ),
    ]
