# Generated by Django 5.1.4 on 2025-01-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_user_wishlist_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='item_ids',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item_ids',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
