# Generated by Django 5.1.4 on 2025-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_wishlist_item_ids_alter_wishlist_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='item_ids',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item_ids',
            field=models.JSONField(default=list),
        ),
    ]
