# Generated by Django 5.1.4 on 2025-01-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_wishlist_item_ids_alter_wishlist_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item_ids',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='store.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
