# Generated by Django 5.1.4 on 2025-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_wishlist_item_ids_alter_wishlist_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='item_ids',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item_ids',
            field=models.JSONField(default=list),
        ),
    ]
